name: Yono 

on:
  push:
    branches:
      - master  # Change this to your default branch name

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.x'  # Change to your desired Flutter version

    - name: Get packages
      run: flutter pub get

    - name: Run tests
      run: flutter test

    - name: Build Windows app
      run: flutter build windows
